// <auto-generated />
using System;
using GestaoAcesso.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoAcesso.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414163613_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoAcesso.Domain.Entities.Aplicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Aplicacoes", (string)null);
                });

            modelBuilder.Entity("GestaoAcesso.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AplicacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Permissoes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("AplicacaoId");

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("GestaoAcesso.Domain.Entities.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcedidoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataConcessao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioAzureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PermissoesEspeciais", (string)null);
                });

            modelBuilder.Entity("GestaoAcesso.Domain.Entities.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioResponsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Unidades", (string)null);
                });

            modelBuilder.Entity("GestaoAcesso.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("AzureUniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Nit")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rg")
                        .HasColumnType("text");

                    b.Property<Guid>("UnidadePrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("AzureUniqueId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("UnidadePrincipalId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PerfilUsuario", b =>
                {
                    b.Property<Guid>("PerfisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioAzureUniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("PerfisId", "UsuarioAzureUniqueId");

                    b.HasIndex("UsuarioAzureUniqueId");

                    b.ToTable("UsuarioPerfis", (string)null);
                });

            modelBuilder.Entity("UnidadeUsuario", b =>
                {
                    b.Property<Guid>("UnidadesSecundariasId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioAzureUniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("UnidadesSecundariasId", "UsuarioAzureUniqueId");

                    b.HasIndex("UsuarioAzureUniqueId");

                    b.ToTable("UsuarioUnidadesSecundarias", (string)null);
                });

            modelBuilder.Entity("GestaoAcesso.Domain.Entities.Perfil", b =>
                {
                    b.HasOne("GestaoAcesso.Domain.Entities.Aplicacao", "Aplicacao")
                        .WithMany("Perfis")
                        .HasForeignKey("AplicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicacao");
                });

            modelBuilder.Entity("GestaoAcesso.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("GestaoAcesso.Domain.Entities.Unidade", "UnidadePrincipal")
                        .WithMany()
                        .HasForeignKey("UnidadePrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadePrincipal");
                });

            modelBuilder.Entity("PerfilUsuario", b =>
                {
                    b.HasOne("GestaoAcesso.Domain.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAcesso.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioAzureUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UnidadeUsuario", b =>
                {
                    b.HasOne("GestaoAcesso.Domain.Entities.Unidade", null)
                        .WithMany()
                        .HasForeignKey("UnidadesSecundariasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAcesso.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioAzureUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoAcesso.Domain.Entities.Aplicacao", b =>
                {
                    b.Navigation("Perfis");
                });
#pragma warning restore 612, 618
        }
    }
}
